### ISSUE TITLE
Credentials Exposed

### ISSUE THREAD

**Issue by csquared** [pethl/netball_usa#1]
https://github.com/pethl/netball_usa/blob/bc533c269de9b0dea8758ed10b8557627d5a20b2/.env#L1-L3

Hi there:
Chris from Bucketeer here. These credentials are on the public internet. I've rolled them and new ones are available in your Heroku app - please keep them private in the future!
Cheers,
Chris

**Comment by pethl** [comment]
Thanks - i was just setting up for the first time and followed a bad instruction somewhere. I've spent 4 hours trying to clean my git history of it - so won't do that again.
